### ISSUE TITLE
Za Warudo | REAK

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#11]
Gilgamesh Moveset:

Zawarudo muss explizit als REAK deklariert werden.

**Comment by Arthania197** [comment]
Ihr stoppt über Arkanmagie die Zeit. Danach wird ein D4 gewürfelt, dieser gibt die Anzahl der Runden an in denen ihr Aktionen wie Buffs und Bewegungen durchführen könnt. Nach den Runden, oder wenn ein Angriff ausgelöst wird, beginnt die Zeit wieder normal zu laufen. Kann als REAK verwendet werden
