### ISSUE TITLE
Glückswurf

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#12]
Glückswürfe im Moment kein zeitlichen refresh Punkt. (Auf Heldenbögen zu korrigieren)

**Comment by Arthania197** [comment]
Glückswurf | Erhält 3 Glückswürfe pro   Spieltag (0:00 Reset) . Darf eines der zwei Würfelergebnisse beliebig   verwendet werden. (Auch bei Gegnern)
