### ISSUE TITLE
Halbierungseffekte (Frage/Balancing)

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#13]
Wenn ein Effekt die Abklingzeit einer Fähigkeit/Gegenstands/etc halbiert, reduziert sich der Wert um die Hälfte der momentane restliche Abklingzeit, oder um die Hälfte der maximalen Abklingzeit.

**Comment by Arthania197** [comment]
Aktuelle Abklingzeit wird halbiert. 
o7

**Comment by Arthania197** [comment]
Revision - Halbiert die insgesamte Abklingzeit
