### ISSUE TITLE
Schwallodem Cynder Moveset Ryuu

### ISSUE THREAD

**Issue by Imutose** [HappyOgre/heroesJourneyWebApp#14]
Schwallodem bei dem Moveset "Gen_42-Formfähigkeiten" fehlt.

**Comment by Arthania197** [comment]
Ihr speit einen Odem aus Schwall auf euren Gegner, ihr ignoriert dabei 3 Stufen Resistenz gegenüber Schwall am Ziel und trefft kritisch | 10R | GW | Etherdrache | 200%
