### ISSUE TITLE
Potential Rebalance needed?

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#16]
Klassentemplates:
Alle Vorschläge sind spezifisch so formuliert, das baseline kein nerf stattfindet (weswegen sie slightly arbitrary wirken)
"||" = logisches oder weil i zfaul bin zum auschreibn

### Krieger:
Protektor (3 Damage weniger; potenziell fine wegen crit reduction; here for completion)
=> Mabye def wert weniger dmg
Letztes Gefecht (statt 30% dmg red => flat value? || double protektor reduction?)
Verwüsten (+2 bonus dmg => können + 1 || level bonus)
Hinrichten (+2 bonus dmg => 2x Können || level bonus || gKRIT)

### Berserker:
Gewaltausbruch (+3 Dmg; potenziell fine wegen 1 crit increase => Können + 3)
Blutdurst (+2 bonus dmg => +Krit bonus dmg)

### Magier:
Rune der Macht (+2 bonus dmg => KE/2 bonus dmg)
Arkanschlag (clarification: "Wenn darauf "Arkanschlag" folgt [...] (max. 2 _Stapel/Damage_(?))
> So wie's sonst formuliert ist, glaub ich können wir die maximale wegnehmen. Ansonsten steht immer explizit dort wenn etwas stapeln kann. Sprache impliziert 1->2 kombo, statt stacken.
Feuerball (Same as Arkanschlag)

=> "Ihr löst eine kleine Arkane Explosion am Ziel aus. Wenn darauf "Arkanschlag" folgt verursacht dieser KE/4 Schaden mehr"
=> "Ihr feuert einen Feuerball auf das Ziel, KRIT von Feuerball ist um 1 erhöht, wenn zuvor "Feuerball" verwendet wurde"

### Mystiker:
Shinobi (+2 bonus dmg => NK/4)
> Hat die Bewandnis das NK/4 für Mystiker schon relevant is, deswegen ned noch a zahl zusätzlich, und gibt erna on average NK/2 pro Runde als bonus dmg (also baseline immer 5 dmg; Goya wären's 8 dmg; wenn voll auf woffn gehst kriagst potenziell 10 aussa + Zusatzaktionen gehst auf die 20dmg pro runde zua)

### Waldläufer:
Markierung des Waldläufers (+3 bonus dmg; betrifft **alle** Fernkampfangriffe, nicht nur die eigenen)
=> "Markierte Ziele erleiden Können x3 Schaden mehr durch **eure** Fernkampfangriffe." (kannst sogoa begleiterangriffe dazuatuan)
> 12 Dmg auf 26+ suid ka thema sein; 3/6/9 dmg is not that much tbh söbst wenn du 6/12/18 draus mochst in am 2target fight)

=> Alternativ mit FK skaliern (siehe Mystiker)
Treuer Begleiter (skaliert mit Nahkampfwaffe; reasonable to assume das ein Fernkämpfer seine Nahkampfwaffe nicht zwingend aufbessert; vermutlich besser auf FK/2)
Gezielter Schuss (+2 bonus dmg) [inconsistent weil sonst der bonus dmg beim betroffenen Zauber steht]
=> Schneller Schuss: (potenziell wos mit hast, weil schnell und thematic? Hast/4 bonus dmg?)

### Schurke:
Verstohlenheit (+3 bonus dmg; possibly offset wegen erleichterung)
> Thoughts: Aus dem Schleichen heraus passiert ned oft, vermutlich 1x pro Kampf außer zu speziellen Situationen. Und aus dem Hinterhalt und aus dem Schleichen **kann** man gleichsetzen:

=> Verstohlenheit: In leichter Dunkelheit zählt ihr als vollständig verborgen, in absoluter dunkelheit seid ihr effektiv unsichtbar
> außer jmd hot truesight; jmd hät darkvision, magic eyes etc. mocht stealth more consistant und gibt da rp mit shadows und so kram, wär a im kampf cool, denk i

=> Tricks des Berufs: "[...] verursachen kritische Treffer und machen KRIT bonusschaden. [...]"
Schattentanz (+2 bonus dmg => No bonus dmg [weils in Tricks of the Trade is])
Tückische Klinge (+2 bonus dmg meucheln) [siehe gezielter schuss für inconsistency in wording]
=> bonus dmg kau ma wegnehmen, theoretisch
Meucheln (gKRIT ausweiden) [siehe gezielter schuss für inconsistency in wording]
=> Ausweiden: "[...], welcher von Tricks des Berufs profitiert, unabhängig eines Hinterhalts, wenn zuvor Meucheln gewirkt wurde."

### Druide:
Gestaltwandel (+2 bonus dmg => Können * 2 dmg) [exists]
Sternenwind (+2 bonus dmg => Lvl dmg) [correct gameplay]
Astrale Ausrichtung (+2 bonus dmg => Lvl *2 dmg) [burst]

### Augmentor:
Nullschleife (+3 bonus dmg; possibly fine weil später 2 leute buffed => lvl/2)

### Beschwörer:
Berschwörerbund (might be fine, da's recht hohe uptime hot; for completion)
- Weltliche (2 dmg reduction)
- Mythische (+ 2 bonus dmg auf crit => +krit auf crit)
Beschwörungsform (Typo, da im Buff "Beschwörungsbund" steht aber die passive "Beschwörerbund" heißt, NBD)

### Avatar:
Gestaltwandel (+2 bonus dmg => Können * 2 dmg) [exists])
Shiakal (+3 bonus dmg; might be fine weil's x3 is => Können +1 bonus dmg) [skaliert vo 15 -> 25 bonus dmg]

### Illusionist:
Trickreiche Gedanken (+3 bonus dmg; kein wert für die Erschwerung für Gegner[QoL beiderseits])
=> Können * 2 bonus dmg || lvl/2 bonus dmg [effektiv 8 oder 10 als ceiling {da lvl30 unrealistisch is im moment}]

### Geisterklinge:
Klingenkampf und Macht der Waffen widersprechen sich; bzw heben sich gegenseitig auf:
Klingenkampf ("[...]maximal eine Waffe beschwören")
Macht der Waffen ("Ihr könnt jetzt bis zu 3 Waffen neben euch beschören[...]")
> Intention is vermutlich das Klingenkampf wirklich geführt wird, Macht der Waffen beschworen und pseudo-selbstständig

=> Klingenkampf "[...] Ihr könnt einmal am Anfang jeder Runde ein Waffenset beschwören. Ihr könnt maximal ein beschworenes Waffenset führen" (Ned perfekt, aber so is zumindest die distinction vo de zwa passive klarer)
Klingentanz (+2 bonus dmg => verdoppeln den dmg) [geht vo WK/4 auf WK/2 und später vo WK/2 auf WK; which is good for burst]
> gute waffen werdn die auf ca 20 WK bringen was ba 1R duration 100 bonus dmg wären auf lvl 10+; this is fine for a burst imo

### Runenritter:
Runenkampf (+5 bonus dmg; might be fine weils an an spontan proc bundn is)
Arkane Macht (+3 bonus dmg => KE/2 bonus dmg) [baseline 5]
Runengeneration (+5 bonus dmg; might be fine weil theme)

### Rufer:
Elementladung (+1 bonus dmg/10EL => Können bonus dmg/10EL) [min. dmg skaliert 5->20]
Magmakammer (+2 bonus dmg => +Krit bonus dmg) [crit based passive, makes sense to me]
Totem des Feuerzorns (+2 bonus dmg; might be fine weil high uptime)
=> +Können bonus dmg

### Mönch:
Protektor (3 damage weniger; might be fine wegen crit reduction)
=> Def wert weniger
Kombobrecher (+2 bonus dmg; might be fine weil nur feelsgood)
=> Heilung -> Def *2 Heilung [shatterpoint is baseline gleich stark wie 5 Heilung wenn ma RSK crittet]
=> Können *2 bonus dmg
Staffeln (potenziell zu einer REAK machn?)

### Hexenmeister:
Herrschaft des Chaos (25% [archaic value]; should be fine though)

Edit: Formatting

**Comment by Arthania197** [comment]
Under review
