### ISSUE TITLE
Spezielle Fähigkeiten, Augmentierte Essenzen etc.

### ISSUE THREAD

**Issue by Arthania197** [HappyOgre/heroesJourneyWebApp#3]
Hey, das ist was über das wir noch nicht geredet haben / ich habs vergessen zu erwähnen.

Geht hier drum, dass manche Sachen die man im Spiel erreichen kann nicht gezielt auch eine Form oder eine Beschwörung oder sonst was sein muss, sondern als Beispiel:

Du kannst roter Drachenaspekt sein, aber musst dafür kein Drache sein. 
Du kannst ein Drache sein aber kein Aspekt.

![image](https://github.com/HappyOgre/gitHubTest/assets/170887701/d7ba983a-1eda-44a5-86eb-891a12594b81)

Sieht so aus die Seite, im endeffekt kann das hier eine Liste sein, ich weiß nur nicht ob wir hierfür eine normale Menüoption machen sollten oben oder nicht, das müssten wir abklären.

Aber generell werden hier 2/3 Werte, meist, zu den Attributen dazu gerechnet (Kann aber genauso einfach nur AT oder ZA sein)
Ich denk das wird hauptsächlich eine Skript sache, aber wir sollten uns überlegen wo wir das einbinden, evtl bei "Quest" weil solche Sachen meistens Storyrelevant sind.

LG

**Comment by HappyOgre** [comment]
done
