### ISSUE TITLE
Buffs und Delayed Damage

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#5]
Wenn delayed damage applied wird (z.B. Living Bomb) wird ein Buff nur eingerechnet wenn er im Moment der Aktion aktiv war, oder wenn er im Moment des Auslösens aktiv war.

Also um Living Bomb Damage zu buffen, welches Szenario muss zutreffen?

**Szenario 1:**
Buff
LB
---wait---

LB explode

**Szenario 2:**
LB
---wait---

Buff
LB explode

**Comment by Arthania197** [comment]
Szenario 2.

I denk mal die anfrage wir in richtung Snapshotting gehn, ansich is bis auf einige wenige spells ned gedacht das irgendwas in HeJo snapshotted.

Aber im endeffekt zählt nur der buff der in der jeweiligen runde gewirkt wird.

Also in den dot runden werden die dots verstärkt durch Buffs der jeweiligen runde.

Und in da explosionsrunde wird die explosion gebuffed von den jeweiligen buffs in der runde


Living Bomb zählt allerdings wenn da dot nicht krittet für die Krit + passive
