### ISSUE TITLE
Ryuu - Pyromane

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#6]
Im Moment sagt nichts im Text aus, dass die Krit-Erhöhung durch einen erfolgreichen kritischen Treffer wieder verloren geht.

Heldenbogen Ryuu, Seite 5, Passive No. 2: Pyromane/Höllenfeuerpyromane

**Comment by Arthania197** [comment]
Immer wenn ihr nicht kritisch trefft erhöht sich KRIT um 1. Der nächste kritische Treffer verursacht euren KRIT-Wert mehr an Schaden. || Wenn Kalagdroog aktiv ist: Erhöht sich euer KRIT um 3. Für jedes Gruppenmitglied das, dass Ziel von Kalagdroog attackiert wird sein KRIT-Multiplikator um 0,5 erhöht. (Während Kalagdroog aktiv ist profitiert ihr nicht mehr vom ersten Teil dieser Passive). Passive wird nach einem kritischen Treffer zurückgesetzt.
