### ISSUE TITLE
Vorteil "Koch"

### ISSUE THREAD

**Issue by AarSaag** [HappyOgre/heroesJourneyWebApp#8]
Der Vorteil Koch gibt noch immer Können im Talent "Zubereiten" welches nicht mehr existiert.

**Comment by Arthania197** [comment]
_Ihr erhaltet Können in „Zubereiten“, falls ihr es noch nicht habt. Während einer Langen Rast könnt Ihr Proviant kochen. Dieser Proviant gibt wenn er verzerrt wird, eine Bonusaktion und LE in höhe eures Könnenwerts mal 2_

Ihr erhaltet Können in „Überlebenskunst“, falls ihr es noch nicht habt. Während einer Langen Rast könnt Ihr Proviant kochen. Dieser Proviant gibt wenn er verzerrt wird, eine Bonusaktion und LE in höhe eures Könnenwerts mal 2

**Comment by Arthania197** [comment]
Korrigiert und auf allen HBs nachgezogen, danke
